export const musicData = [
  {
    backgroundImage: "./assets/images/poster-1.jpg",
    posterUrl: "./assets/images/poster-1.jpg",
    title: "Aayi Nai - Stree 2 ",
    album: "Stree 2",
    year: 2024,
    artist: "Pawan Singh",
    musicPath: "./assets/music/music-1.mp3",
  },
  {
    backgroundImage: "./assets/images/poster-2.jpg",
    posterUrl: "./assets/images/poster-2.jpg",
    title: "O Sajna",
    album: " Ek THA RAJA",
    year: 2024,
    artist: "Badshah X DIVINE",
    musicPath: "./assets/music/music-2.mp3",
  },
  {
    backgroundImage: "./assets/images/poster-3.jpg",
    posterUrl: "./assets/images/poster-3.jpg",
    title: "Ishq Nachaawe",
    album: "Kho Gaye Hum Kahan ",
    year: 2024,
    artist: "Karan Kanchan X Rashmeet Kaur",
    musicPath: "./assets/music/music-3.mp3",
  },
  {
    backgroundImage: "./assets/images/poster-4.jpg",
    posterUrl: "./assets/images/poster-4.jpg",
    title: "Prabh - 9:45",
    album: "Punjabi",
    year: 2024,
    artist: "Prabh Singh",
    musicPath: "./assets/music/music-4.mp3",
  },
  {
    backgroundImage: "./assets/images/poster-5.jpg",
    posterUrl: "./assets/images/poster-5.jpg",
    title: "Khayaal",
    album: "Khayaal",
    year: 2024,
    artist: "Talwiinder",
    musicPath: "./assets/music/music-5.mp3",
  },

  {
    backgroundImage: "./assets/images/poster-6.jpg",
    posterUrl: "./assets/images/poster-6.jpg",
    title: "Still Rollin",
    album: "Still Rollin",
    year: 2024,
    artist: "Shubh",
    musicPath: "./assets/music/music-6.mp3",
  },

  {
    backgroundImage: "./assets/images/poster-7.jpg",
    posterUrl: "./assets/images/poster-7.jpg",
    title: "Manike",
    album: "Thank God",
    year: 2024,
    artist: "Yohani X Jubin",
    musicPath: "./assets/music/music-7.mp3",
  },

  {
    backgroundImage: "./assets/images/poster-8.png",
    posterUrl: "./assets/images/poster-8.png",
    title: "Nonstop Punjabi Mashup 2024",
    album: "Nonstop Punjabi Mashup",
    year: 2024,
    artist: "Nonstop Punjabi Mashup 2024",
    musicPath: "./assets/music/music-8.mp3",
  },
];
